### ISSUE TITLE
Could not find ../data/test

### ISSUE THREAD

**Issue by SJHBXShub** [Belval/CRNN#10]
Hello, I want to try this command 
**python3 run.py -ex ../data/test --test --restore**
But I found there is no **../data/test** in the folder of CRNN
Could you help me?

**Comment by Belval** [comment]
I do not upload datasets to github as they limit repo size to 1 GB.

Fortunately,you can create synthetic data similar to the one I used by using my project https://github.com/Belval/TextRecognitionDataGenerator just install the required dependencies and run `python3 run.py -c 1000 -w 1` to get some data.

Hope it helps!

**Comment by SJHBXShub** [comment]
Hi, I have used TextRecongnitionDataGenerator to data set. And I found some problems:
1. The sentences generated by TextRecongnitionDataGenerator contain some characters that are not contained in CHAR_VECTOR, like & or blank space. I tried to add such missing characters to the CHAR_VECTOR by amending the config.py, but I confront some errors.

2. when I train the mode, I found the loss is inf. Have you ever trained the model to convergent?
I am looking for your suggestion. Thank your!

**Comment by Belval** [comment]
The infinite loss is a problem I have not fixed yet as I do not know what causes it. Fortunately the model converge regardless in the sense that it does output better predictions.

For the test set, I'll give you a link to my own dataset later today. In the meantime, make sure that you use `-w 1` when generating to remove spaces from your samples. As for the &, there are probably no more than a handful so you can just search them in the dataset and delete them.

**Comment by Belval** [comment]
Please try this dataset: https://node1.belval.org/test_dataset.zip

**Comment by Belval** [comment]
Closing for lack of response.
