### ISSUE TITLE
python run.py -ex ../samples --test --restore

### ISSUE THREAD

**Issue by atVoidYX** [Belval/CRNN#11]
I just want to test it，and change  ../data/test to ../samples,the folder "samples" also have some image.
But I don not get anything except the flowing：
-----------------------------
Restoring
Checkpoint is valid
0
Loading data
Testing
-----------------------------
then，it exits.

**Comment by atVoidYX** [comment]
ok，I have fixed it.you use the special way to name the "jpg" files and then check the max_char_count

**Comment by pribadihcr** [comment]
@atVoidYX  how do you did?

**Comment by atVoidYX** [comment]
@pribadihcr 這個項目中，妳需要滿足兩個條件，足夠數量的圖片（mini batch需要），並且以特定方式命名，因為這個項目的作者使用的圖片是自己生成的，他在代碼中通過命名判斷了字符長度，大於24個字符不會被識別，loaddata結果會是空。至於為何會是24，作者參考了原來paper。
我記得在壹個issue中作者給出了他的壹個測試集，妳可以去下載，當妳也可以通過作者在readme中的鏈接使用另壹個項目生成圖片。
最后希望我的繁体并没出现错误。

**Comment by Belval** [comment]
@pribadihcr, the dataset @atVoidYX is referring to can be downloaded here: belv.al/6e839

**Comment by atVoidYX** [comment]
@Belval sorry，I have seen pribadihcr‘s info on github and known he lives in Taiwan，so I use Chinese to response. you can read Chinese?I was very surprised.
