### ISSUE TITLE
continuous repetition letters of the OCR

### ISSUE THREAD

**Issue by evanfly** [Belval/CRNN#19]
hi Belval , when i retrain the crnn code ,i found that if there were continuous repetition letters of the OCR, the result offer missed the repetition letters and outputed the single letter . Such as the Ground truth of the OCR is '0870011' , '37075337' , and the Prediction is '08701' , '3707537' .  If there were no  continuous repetition letters ,the result was correct . My training data only include digital  provide by your project https://github.com/Belval/TextRecognitionDataGenerator .  
Is it the problem of the CTC ? How can i to solve this problem? 
ths!

**Comment by Belval** [comment]
This is a known tradeoff with CTC, to my knowledge. Usually researchers will use a lexicon to overcome this.

In the meantime, you can use `merge_repeated=False` as an additional parameter in the `ctc_beam_search_decoder` op to prevent merging. Do note that this will probably duplicate some letters.

https://www.tensorflow.org/api_docs/python/tf/nn/ctc_beam_search_decoder

**Comment by evanfly** [comment]
ths . solved
