### ISSUE TITLE
result in ICDAR2013

### ISSUE THREAD

**Issue by wushilian** [Belval/CRNN#4]
what's the result in ICDAR2013,my result is lower than paper

**Comment by Belval** [comment]
Hi,

I am still working on it. I'll report back when I get results.

**Comment by wushilian** [comment]
@Belval Hi,did you get results?

**Comment by Belval** [comment]
No, it hardly converges and never comes close to the paper performance.

I am having trouble understanding Tensorflow's CTC operation (which is probably the cause of the weak performance). If you know any resource that explains how to use it I would look it up.

**Comment by wushilian** [comment]
I saw your code,and I don't think the problem is ctc.I use the ctc like you,but I got 80% acc in ICDAR2013

**Comment by Belval** [comment]
That's great, is you code on github? I'd love to take a look and hopefully figure out where I did wrong.

**Comment by wushilian** [comment]
@Belval https://github.com/wushilian/STN_CNN_LSTM_CTC_TensorFlow

**Comment by Belval** [comment]
@wushilian is the ICDAR2013 dataset still available? The website I found doesn't accept registrations anymore.

**Comment by Belval** [comment]
Closing for lack of response.
