### ISSUE TITLE
How can I accelerate training process using gpu？

### ISSUE THREAD

**Issue by awonderfullife** [Belval/CRNN#7]
it seems that it only uses cpu to train the model...

**Comment by Belval** [comment]
It does not! It's just that my batch generator in this particular project is nothing short of terrible and it pretty much always have some calculations to do.

I'm working on a different batch generator that should be available in the next few days.

You can test my claims by running `watch -n 1 nvidia-smi` on your Linux box and you should see a usage peak every 2-3 seconds depending on batch size.

Please also do keep in mind that the model in the original paper took 50 hours to train so it's normal if it seems to be a slow learner.

**Comment by Belval** [comment]
There is something wrong with the whole training pipeline I think. Unfortunately, I have been quite short on time recently so I don't know when I'll have the time to work on this.

Do consider what I wrote above though: the model does take time to train and you will see small peaks of GPU activity for 1-2 seconds of 100%. I think it's just data-starved.

**Comment by TccccD** [comment]
Yes, it have small peaks of GPU activity for 1-2 seconds of 100%, but after that, it also have 5mins 0%. @Belval

**Comment by TccccD** [comment]
oh, I find CTCBeamSearchDecoder 200s+ cost, it use cpu.
