### ISSUE TITLE
What does seq_len means?

### ISSUE THREAD

**Issue by wujiabin8894** [Belval/CRNN#8]
Thank you for sharing this wonderful project. It works quite well for my number recg problem.
But I have some confusion.

In feed_dict, self.__seq_len: [self.__max_char_count] * self.__data_manager.batch_size, 
and
max_char_count = reshaped_cnn_output.get_shape().as_list()[1] .
I'm not quite understand of that. Should seq_len be the width of img after cnn part of shape(batchsize, ?)

Sorry for my poor English.

**Comment by Belval** [comment]
After the CNN part of the model, the image will become a tensor of size 24x512 (if you use a width of 100px). The 24 represents the maximum number of characters that we could "read" and therefore the number of timesteps that the RNN should process.

I would recommend reading the paper as the author explains it quite well.

**Comment by wujiabin8894** [comment]
3q
