### ISSUE TITLE
Use effect

### ISSUE THREAD

**Issue by ajiaxiaoyi** [Belval/CRNN#9]
Can I see the actual recognition effect of your program after training?

**Comment by Belval** [comment]
Coupd you clarify what you mean by the actual recognition effect?

If it's testing you can call the CLI with `--test` and it should work iirc.

**Comment by ajiaxiaoyi** [comment]
OK, I know.thanks.

**Comment by Belval** [comment]
I don't quite remember how I used it, if you run into any issue please report back so I can fix them :)

**Comment by ajiaxiaoyi** [comment]
OK!

**Comment by Belval** [comment]
Closing because user never reported back. Feel free to reopen should you need help.
